export interface PricingInnerInterface {
  current: string;
  id?: string;
  month_price: number;
  year_price: number;
  channel?: number;
  posts_per_month: number;
  team_members: boolean;
  max_organizations: number;
  max_platforms: number;
  community_features: boolean;
  featured_by_appswifts: boolean;
  ai: boolean;
  import_from_channels: boolean;
  image_generator?: boolean;
  image_generation_count: number;
  generate_videos: number;
  public_api: boolean;
  webhooks: number;
  autoPost: boolean;
  inbox: boolean;
  campaigns: boolean;
  leads: boolean;
  isDefault?: boolean;
  isActive?: boolean;
}
export interface PricingInterface {
  [key: string]: PricingInnerInterface;
}
export const pricing: PricingInterface = {
  FREE: {
    id: 'free',
    current: 'FREE',
    month_price: 0,
    year_price: 0,
    channel: 0,
    image_generation_count: 0,
    posts_per_month: 0,
    team_members: false,
    max_organizations: 1,
    max_platforms: 0,
    community_features: false,
    featured_by_appswifts: false,
    ai: false,
    import_from_channels: false,
    image_generator: false,
    public_api: false,
    webhooks: 0,
    autoPost: false,
    generate_videos: 0,
    inbox: false,
    campaigns: false,
    leads: false,
    isDefault: true,
    isActive: true,
  },
  STANDARD: {
    id: 'standard',
    current: 'STANDARD',
    month_price: 29,
    year_price: 278,
    channel: 5,
    posts_per_month: 400,
    image_generation_count: 20,
    team_members: false,
    max_organizations: 1,
    max_platforms: 5,
    community_features: false,
    featured_by_appswifts: false,
    ai: true,
    import_from_channels: true,
    image_generator: false,
    public_api: true,
    webhooks: 2,
    autoPost: false,
    generate_videos: 3,
    inbox: true,
    campaigns: false,
    leads: true,
    isDefault: false,
    isActive: true,
  },
  TEAM: {
    id: 'team',
    current: 'TEAM',
    month_price: 39,
    year_price: 374,
    channel: 10,
    posts_per_month: 1000000,
    image_generation_count: 100,
    community_features: true,
    team_members: true,
    max_organizations: 3,
    max_platforms: 10,
    featured_by_appswifts: true,
    ai: true,
    import_from_channels: true,
    image_generator: true,
    public_api: true,
    webhooks: 10,
    autoPost: true,
    generate_videos: 10,
    inbox: true,
    campaigns: true,
    leads: true,
    isDefault: false,
    isActive: true,
  },
  PRO: {
    id: 'pro',
    current: 'PRO',
    month_price: 49,
    year_price: 470,
    channel: 30,
    posts_per_month: 1000000,
    image_generation_count: 300,
    community_features: true,
    team_members: true,
    max_organizations: 5,
    max_platforms: 30,
    featured_by_appswifts: true,
    ai: true,
    import_from_channels: true,
    image_generator: true,
    public_api: true,
    webhooks: 30,
    autoPost: true,
    generate_videos: 30,
    inbox: true,
    campaigns: true,
    leads: true,
    isDefault: false,
    isActive: true,
  },
  ULTIMATE: {
    id: 'ultimate',
    current: 'ULTIMATE',
    month_price: 99,
    year_price: 950,
    channel: 100,
    posts_per_month: 1000000,
    image_generation_count: 500,
    community_features: true,
    team_members: true,
    max_organizations: 10,
    max_platforms: 100,
    featured_by_appswifts: true,
    ai: true,
    import_from_channels: true,
    image_generator: true,
    public_api: true,
    webhooks: 10000,
    autoPost: true,
    generate_videos: 60,
    inbox: true,
    campaigns: true,
    leads: true,
    isDefault: false,
    isActive: true,
  },
};
